[task_config]
includes = [".config/mise-lib/virtual_tasks.toml", ".config/mise-lib"]

[tasks.test]
depends = ["rust:test"]
description = "Run tests"

[tasks.fmt]
depends = ["rust:fmt"]
description = "Format source"

[tasks.fmt-check]
depends = ["rust:fmt-check"]
description = "Check formatting"

[tasks.lint]
depends = ["rust:lint"]
description = "Lint the project"

[tasks.lint-fix]
depends = ["rust:lint-fix"]
description = "Run lint fixers"

[tasks.ci]
depends = ["test", "fmt-check", "lint"]
description = "Run CI tasks"

[tasks.build]
depends = ["rust:build"]
description = "Build the project in debug mode"
sources = ["api/src/**/*.rs", "controller/src/**/*.rs", "**/Cargo.lock", "**/Cargo.toml"]
outputs = ["target/debug/yakup"]

[tasks.release-build]
depends = ["rust:release-build"]
description = "Build the project"
sources = ["api/src/**/*.rs", "controller/src/**/*.rs", "**/Cargo.lock", "**/Cargo.toml"]
outputs = ["target/release/yakup.*.aarch64-unknown-linux-musl", "target/release/yakup.*.armv7-unknown-linux-musleabihf", "target/release/yakup.*.x86_64-unknown-linux-musl"]

[tasks.generate-crd-manifests]
depends = ["rust:setup"]
description = "Generates the CRD manifests"
sources = ["api/src/**/*.rs", "api/Cargo.lock", "**/Cargo.toml"]
outputs = ["{{ config_root }}/mise-output/manifests.yaml"]
run = """
cargo run --bin crd
output_directory="${MISE_CONFIG_ROOT}/mise-output/"
mkdir --parents "${output_directory}"
mv target/crd/manifests.yaml "${output_directory}"
"""

[tasks.manifests]
description = "Generate all manifests needed for deploy"
outputs = ["${MISE_CONFIG_ROOT}/mise-output/*.yaml"]
usage = '''
arg "<image>" help="Image to use in manifests"
'''
run = """
    mise run k8s:manifests ${usage_image}
    mise run generate-crd-manifests
"""
