[project]
name = "main"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiometer>=0.5.0",
    "dagger-io",
    "jinja2>=3.1.4",
]

[tool.uv.sources]
dagger-io = { path = "sdk", editable = true }

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"
